version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "v2"
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "v2"
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "ci"
    open-pull-requests-limit: 3
