# Generated by Django 4.2.29 on 2026-03-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, default='', help_text='Google profile photo URL, updated on each login', max_length=500),
        ),
    ]
