# Generated by Django 4.2.29 on 2026-03-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_set_superuser_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('triage_lead', 'Triage Lead'), ('member', 'Team Member')], default='member', max_length=20),
        ),
    ]
