# Generated by Django 5.2.12 on 2026-03-11 09:58

from django.db import migrations


SEED_DATA = [
    # Feature flags
    {
        "key": "ai_triage_enabled",
        "value": "true",
        "value_type": "bool",
        "category": "feature_flags",
        "description": "Enable/disable AI triage processing",
    },
    {
        "key": "chat_notifications_enabled",
        "value": "true",
        "value_type": "bool",
        "category": "feature_flags",
        "description": "Enable/disable Google Chat notifications",
    },
    {
        "key": "eod_email_enabled",
        "value": "true",
        "value_type": "bool",
        "category": "feature_flags",
        "description": "Enable/disable daily EOD email report",
    },
    # Polling config
    {
        "key": "poll_interval_minutes",
        "value": "5",
        "value_type": "int",
        "category": "polling",
        "description": "Minutes between Gmail poll cycles",
    },
    {
        "key": "max_consecutive_failures",
        "value": "3",
        "value_type": "int",
        "category": "polling",
        "description": "Circuit breaker threshold",
    },
    {
        "key": "monitored_inboxes",
        "value": "info@vidarbhainfotech.com,sales@vidarbhainfotech.com",
        "value_type": "str",
        "category": "polling",
        "description": "Comma-separated list of monitored inbox addresses",
    },
    # Quiet hours
    {
        "key": "quiet_hours_start",
        "value": "20",
        "value_type": "int",
        "category": "quiet_hours",
        "description": "Quiet hours start (24h IST)",
    },
    {
        "key": "quiet_hours_end",
        "value": "8",
        "value_type": "int",
        "category": "quiet_hours",
        "description": "Quiet hours end (24h IST)",
    },
    # Business hours
    {
        "key": "business_hours_start",
        "value": "8",
        "value_type": "int",
        "category": "business_hours",
        "description": "Business hours start (24h IST)",
    },
    {
        "key": "business_hours_end",
        "value": "21",
        "value_type": "int",
        "category": "business_hours",
        "description": "Business hours end (24h IST)",
    },
]


def seed_config(apps, schema_editor):
    SystemConfig = apps.get_model("core", "SystemConfig")
    for entry in SEED_DATA:
        SystemConfig.objects.update_or_create(
            key=entry["key"],
            defaults=entry,
        )


def unseed_config(apps, schema_editor):
    SystemConfig = apps.get_model("core", "SystemConfig")
    keys = [entry["key"] for entry in SEED_DATA]
    SystemConfig.objects.filter(key__in=keys).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_config, unseed_config),
    ]
