from django.urls import path

from . import views

app_name = "emails"

urlpatterns = [
    path("", views.thread_list, name="thread_list"),
    path("legacy/", views.email_list, name="email_list"),
    # Bulk action endpoints (before threads/<int:pk>/ to avoid URL conflicts)
    path("threads/bulk-assign/", views.bulk_assign, name="bulk_assign"),
    path("threads/bulk-mark-irrelevant/", views.bulk_mark_irrelevant, name="bulk_mark_irrelevant"),
    path("threads/bulk-undo/", views.bulk_undo, name="bulk_undo"),
    # Thread-level endpoints
    path("threads/<int:pk>/detail/", views.thread_detail, name="thread_detail"),
    path("threads/<int:pk>/note/", views.add_note_view, name="add_note"),
    path("threads/<int:pk>/assign/", views.assign_thread_view, name="assign_thread"),
    path("threads/<int:pk>/status/", views.change_thread_status_view, name="change_thread_status"),
    path("threads/<int:pk>/claim/", views.claim_thread_view, name="claim_thread"),
    path("threads/<int:pk>/reassign/", views.reassign_thread_view, name="reassign_thread"),
    path("threads/<int:pk>/heartbeat/", views.viewer_heartbeat, name="viewer_heartbeat"),
    path("threads/<int:pk>/clear-viewer/", views.clear_viewer, name="clear_viewer"),
    path("threads/<int:pk>/whitelist-sender/", views.whitelist_sender_from_thread, name="whitelist_thread_sender"),
    path("threads/<int:pk>/accept-suggestion/", views.accept_thread_suggestion, name="accept_thread_suggestion"),
    path("threads/<int:pk>/reject-suggestion/", views.reject_thread_suggestion, name="reject_thread_suggestion"),
    path("threads/<int:pk>/mark-unread/", views.mark_thread_unread, name="mark_thread_unread"),
    path("threads/<int:pk>/edit-summary/", views.edit_ai_summary, name="edit_ai_summary"),
    path("threads/<int:pk>/edit-category/", views.edit_category, name="edit_category"),
    path("threads/<int:pk>/edit-priority/", views.edit_priority, name="edit_priority"),
    path("threads/<int:pk>/edit-status/", views.edit_status, name="edit_status"),
    path("threads/<int:pk>/context-menu/", views.thread_context_menu, name="thread_context_menu"),
    path("threads/<int:pk>/mark-spam/", views.mark_spam, name="mark_spam"),
    path("threads/<int:pk>/mark-not-spam/", views.mark_not_spam, name="mark_not_spam"),
    path("threads/<int:pk>/mark-irrelevant/", views.mark_irrelevant, name="mark_irrelevant"),
    path("threads/<int:pk>/revert-irrelevant/", views.revert_irrelevant, name="revert_irrelevant"),
    path("spam-feedback/<int:pk>/undo/", views.undo_spam_feedback, name="undo_spam_feedback"),
    path("settings/sender/<int:pk>/unblock/", views.unblock_sender, name="unblock_sender"),
    path("<int:pk>/detail/", views.email_detail, name="email_detail"),
    path("<int:pk>/assign/", views.assign_email_view, name="assign_email"),
    path("<int:pk>/status/", views.change_status_view, name="change_status"),
    path("<int:pk>/claim/", views.claim_email_view, name="claim_email"),
    path("<int:pk>/accept-ai/", views.accept_ai_suggestion, name="accept_ai_suggestion"),
    path("<int:pk>/reject-ai/", views.reject_ai_suggestion, name="reject_ai_suggestion"),
    path("settings/", views.settings_view, name="settings"),
    path("settings/rules/", views.settings_rules_save, name="settings_rules_save"),
    path("settings/visibility/", views.settings_visibility_save, name="settings_visibility_save"),
    path("settings/sla/", views.settings_sla_save, name="settings_sla_save"),
    path("settings/inboxes/", views.settings_inboxes_save, name="settings_inboxes_save"),
    path("settings/config/", views.settings_config_save, name="settings_config_save"),
    path("settings/webhooks/", views.settings_webhooks_save, name="settings_webhooks_save"),
    path("settings/whitelist/add/", views.whitelist_add, name="whitelist_add"),
    path("settings/whitelist/<int:pk>/delete/", views.whitelist_delete, name="whitelist_delete"),
    path("<int:pk>/whitelist-sender/", views.whitelist_sender, name="whitelist_sender"),
    path("reports/", views.reports_view, name="reports"),
    path("activity/", views.activity_log, name="activity_log"),
    path("inspect/", views.inspect, name="inspect"),
    path("inspect/force-poll/", views.force_poll, name="force_poll"),
]
