# Generated by Django 5.2.12 on 2026-03-09 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('gmail_id', models.CharField(blank=True, default='', max_length=255)),
                ('gmail_thread_id', models.CharField(blank=True, default='', max_length=255)),
                ('gmail_labels', models.JSONField(blank=True, default=list)),
                ('from_address', models.EmailField(max_length=254)),
                ('from_name', models.CharField(blank=True, default='', max_length=255)),
                ('to_inbox', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('body', models.TextField(blank=True, default='')),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField()),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('priority', models.CharField(blank=True, default='', max_length=50)),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('ai_draft_reply', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('replied', 'Replied'), ('closed', 'Closed')], default='new', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_by_emails', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='AttachmentMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=255)),
                ('size_bytes', models.PositiveIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('gmail_attachment_id', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='emails.email')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
