# Generated by Django 4.2.29 on 2026-03-14 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0006_widen_attachment_id_and_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpamWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry', models.CharField(db_index=True, max_length=255)),
                ('entry_type', models.CharField(choices=[('email', 'Email'), ('domain', 'Domain')], max_length=10)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whitelist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('entry', 'entry_type')},
            },
        ),
    ]
