# Generated by Django 4.2.29 on 2026-03-15 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0007_spamwhitelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('reassigned', 'Reassigned'), ('status_changed', 'Status Changed'), ('acknowledged', 'Acknowledged'), ('closed', 'Closed'), ('auto_assigned', 'Auto-Assigned'), ('claimed', 'Claimed'), ('sla_breached', 'SLA Breached'), ('priority_bumped', 'Priority Bumped'), ('new_email_received', 'New Email Received'), ('reopened', 'Reopened'), ('thread_created', 'Thread Created')], max_length=30),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='emails.email'),
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gmail_thread_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_sender', models.CharField(blank=True, default='', max_length=500)),
                ('last_sender_address', models.EmailField(blank=True, default='', max_length=254)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('closed', 'Closed')], default='new', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('sla_ack_deadline', models.DateTimeField(blank=True, null=True)),
                ('sla_respond_deadline', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('priority', models.CharField(blank=True, default='', max_length=50)),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('ai_draft_reply', models.TextField(blank=True, default='')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_by_threads', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.AddField(
            model_name='activitylog',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='emails.thread'),
        ),
        migrations.AddField(
            model_name='email',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='emails.thread'),
        ),
    ]
