# Generated by Django 4.2.29 on 2026-03-15 05:38

from django.db import migrations


def wipe_existing_data(apps, schema_editor):
    """Clean slate: hard-delete all existing Email, ActivityLog, and AttachmentMetadata records.

    This is intentional — the Thread model fundamentally changes how emails are organized,
    so existing data (which lacks thread associations) must be cleared. The production
    instance will re-poll emails from Gmail after deployment.
    """
    Email = apps.get_model("emails", "Email")
    ActivityLog = apps.get_model("emails", "ActivityLog")
    AttachmentMetadata = apps.get_model("emails", "AttachmentMetadata")
    # Hard delete (bypasses SoftDeleteModel) — clean slate
    AttachmentMetadata.objects.all().delete()
    ActivityLog.objects.all().delete()
    Email.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0008_thread_model'),
    ]

    operations = [
        migrations.RunPython(wipe_existing_data, migrations.RunPython.noop),
    ]
