# Generated by Django 4.2.29 on 2026-03-15 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0010_wipe_existing_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('reassigned', 'Reassigned'), ('status_changed', 'Status Changed'), ('acknowledged', 'Acknowledged'), ('closed', 'Closed'), ('auto_assigned', 'Auto-Assigned'), ('claimed', 'Claimed'), ('sla_breached', 'SLA Breached'), ('priority_bumped', 'Priority Bumped'), ('new_email_received', 'New Email Received'), ('reopened', 'Reopened'), ('thread_created', 'Thread Created'), ('note_added', 'Note Added'), ('mentioned', 'Mentioned')], max_length=30),
        ),
        migrations.CreateModel(
            name='InternalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_notes', to=settings.AUTH_USER_MODEL)),
                ('mentioned_users', models.ManyToManyField(blank=True, related_name='mentioned_in_notes', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='emails.thread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
