# Generated by Django 4.2.29 on 2026-03-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0012_threadviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='is_spam',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='email',
            name='priority',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='email',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('exhausted', 'Exhausted')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='email',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('replied', 'Replied'), ('closed', 'Closed')], db_index=True, default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='email',
            name='to_inbox',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='thread',
            name='category',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='thread',
            name='priority',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='thread',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('closed', 'Closed')], db_index=True, default='new', max_length=20),
        ),
    ]
