# Generated by Django 4.2.29 on 2026-03-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0013_alter_email_is_spam_alter_email_priority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField()),
                ('status', models.CharField(db_index=True, max_length=20)),
                ('emails_found', models.IntegerField(default=0)),
                ('emails_processed', models.IntegerField(default=0)),
                ('spam_filtered', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('skipped_reason', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('reassigned', 'Reassigned'), ('status_changed', 'Status Changed'), ('acknowledged', 'Acknowledged'), ('closed', 'Closed'), ('auto_assigned', 'Auto-Assigned'), ('claimed', 'Claimed'), ('sla_breached', 'SLA Breached'), ('priority_bumped', 'Priority Bumped'), ('new_email_received', 'New Email Received'), ('reopened', 'Reopened'), ('thread_created', 'Thread Created'), ('note_added', 'Note Added'), ('mentioned', 'Mentioned'), ('ai_summary_edited', 'AI Summary Edited')], max_length=30),
        ),
    ]
