# Generated by Django 4.2.29 on 2026-03-15 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0014_polllog_alter_activitylog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenderReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_address', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('spam_count', models.PositiveIntegerField(default=0)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='email',
            name='ai_confidence',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='thread',
            name='ai_confidence',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='thread',
            name='category_overridden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thread',
            name='priority_overridden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('reassigned', 'Reassigned'), ('status_changed', 'Status Changed'), ('acknowledged', 'Acknowledged'), ('closed', 'Closed'), ('auto_assigned', 'Auto-Assigned'), ('claimed', 'Claimed'), ('sla_breached', 'SLA Breached'), ('priority_bumped', 'Priority Bumped'), ('new_email_received', 'New Email Received'), ('reopened', 'Reopened'), ('thread_created', 'Thread Created'), ('note_added', 'Note Added'), ('mentioned', 'Mentioned'), ('ai_summary_edited', 'AI Summary Edited'), ('spam_marked', 'Spam Marked'), ('spam_unmarked', 'Spam Unmarked'), ('priority_changed', 'Priority Changed'), ('category_changed', 'Category Changed')], max_length=30),
        ),
        migrations.CreateModel(
            name='SpamFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_verdict', models.BooleanField()),
                ('user_verdict', models.BooleanField()),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spam_feedbacks', to='emails.email')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spam_feedbacks', to='emails.thread')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spam_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssignmentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('reassigned', 'Reassigned'), ('auto_assigned', 'Auto-Assigned')], max_length=20)),
                ('confidence_at_time', models.CharField(blank=True, max_length=10, null=True)),
                ('actual_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_assignments', to=settings.AUTH_USER_MODEL)),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_feedbacks', to='emails.email')),
                ('suggested_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_assignments', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_feedbacks', to='emails.thread')),
                ('user_who_acted', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThreadReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='emails.thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_read_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('thread', 'user')},
            },
        ),
    ]
