# Generated by Django 4.2.29 on 2026-03-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0015_v250_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='is_auto_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
