# Generated by Django 4.2.29 on 2026-03-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0016_add_thread_is_auto_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('reassigned', 'Reassigned'), ('status_changed', 'Status Changed'), ('acknowledged', 'Acknowledged'), ('closed', 'Closed'), ('auto_assigned', 'Auto-Assigned'), ('claimed', 'Claimed'), ('sla_breached', 'SLA Breached'), ('priority_bumped', 'Priority Bumped'), ('new_email_received', 'New Email Received'), ('reopened', 'Reopened'), ('thread_created', 'Thread Created'), ('note_added', 'Note Added'), ('mentioned', 'Mentioned'), ('ai_summary_edited', 'AI Summary Edited'), ('spam_marked', 'Spam Marked'), ('spam_unmarked', 'Spam Unmarked'), ('priority_changed', 'Priority Changed'), ('category_changed', 'Category Changed'), ('marked_irrelevant', 'Marked Irrelevant'), ('reverted_irrelevant', 'Reverted to New')], max_length=30),
        ),
        migrations.AlterField(
            model_name='thread',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('closed', 'Closed'), ('irrelevant', 'Irrelevant')], db_index=True, default='new', max_length=20),
        ),
    ]
